import type { TemplateId } from '../shared/model.js';

export interface TemplateDefinition {
  id: TemplateId; version: 1; name: string; background: string; foreground: string; muted: string;
  line: string; panel: string; accent: string; heroLabel: string; heroTitle: string; css: string;
}

export const templates: Record<TemplateId, TemplateDefinition> = {
  editorial: {
    id: 'editorial', version: 1, name: '白昼 · Editorial', background: '#f5f1e9', foreground: '#292722', muted: '#827c72',
    line: '#d8d0c3', panel: '#ebe5da', accent: '#937754', heroLabel: 'THE WEDDING COLLECTION', heroTitle: 'A day.\nA lifetime.',
    css: `.cover-title{font-weight:400;letter-spacing:-.065em}.cover-kicker{border-top:1px solid var(--line);padding-top:20px}.chapter-heading{font-weight:450}.comparison-frame{background:#e6e0d6}.signature-mark{font-style:italic}.delivery-heading{border-left:2px solid var(--accent);padding-left:14px}.cover-ornament{border-radius:50% 50% 0 0;transform:rotate(-12deg)}`,
  },
  cinematic: {
    id: 'cinematic', version: 1, name: '夜幕 · Cinematic', background: '#151715', foreground: '#eeeee6', muted: '#a1a399',
    line: '#3c4038', panel: '#22261f', accent: '#b7b88c', heroLabel: 'A STORY IN MOTION', heroTitle: 'Every frame,\nforever.',
    css: `.cover-title{font-weight:350;letter-spacing:-.06em;font-style:italic}.cover-kicker{color:var(--accent)}.cover{background:radial-gradient(ellipse at 90% 10%,#414a2d30,transparent 65%)}.chapter-heading{font-weight:350}.comparison-frame{background:#080b09}.signature-mark{font-style:italic}.cover-ornament{border-radius:0;transform:rotate(0deg);opacity:.22}.cover-ornament:after{inset:12px;border-radius:0}.delivery-heading{border-bottom:1px solid var(--line);padding-bottom:16px}`,
  },
};

export const PAGE_WIDTH = 432;
export const PAGE_HEIGHT = 768;
export const PAGE_CONTENT_HEIGHT = 648;

export const sharedCss = `
*{box-sizing:border-box}html{margin:0;background:var(--background);color:var(--foreground);-webkit-print-color-adjust:exact;print-color-adjust:exact}
body{margin:0;font-family:'Studio Sans','Noto Sans CJK SC','Microsoft YaHei',sans-serif;font-size:13px;font-weight:400;line-height:1.9;font-synthesis:none}
.render-root{width:432px;margin:0 auto;background:var(--background)}.flow{padding:32px}.masthead,.page-masthead{display:flex;justify-content:space-between;align-items:flex-start;font-size:9px;letter-spacing:.15em;line-height:1.6;text-transform:uppercase;color:var(--muted)}
.masthead{padding-bottom:24px;border-bottom:1px solid var(--line);margin-bottom:24px}.brand-name{max-width:75%;overflow-wrap:anywhere}.brand-logo{max-width:115px;max-height:35px;object-fit:contain;display:block}.edition{font-family:'Studio Serif',Georgia,serif;font-style:italic;letter-spacing:0;font-size:12px}
.unit{margin:0 0 18px;overflow-wrap:anywhere;min-width:0}.unit:last-child{margin-bottom:0}.cover{position:relative;min-height:548px;padding:14px 0 30px;display:flex;flex-direction:column;justify-content:space-between}.cover-kicker{font-size:9px;letter-spacing:.2em;position:relative;z-index:1}.cover-title{font-family:'Studio Serif',Georgia,serif;font-size:67px;line-height:1.06;margin:35px 0 40px;position:relative;z-index:1;white-space:pre-line}.cover-ornament{position:absolute;width:200px;height:275px;border:1px solid var(--accent);right:-8px;top:93px;opacity:.28}.cover-ornament:after{content:'';position:absolute;inset:9px;border:1px solid var(--accent);border-radius:inherit}.cover-bottom{position:relative;z-index:1}.salutation{font-size:12px;color:var(--muted);margin:0 0 8px}.couple-names{font-size:27px;font-weight:400;letter-spacing:.05em;line-height:1.45;margin:0 0 20px}.date-line{display:flex;justify-content:space-between;gap:12px;border-top:1px solid var(--line);padding-top:15px;font-size:10px;color:var(--muted)}.date-label{font-size:8px;letter-spacing:.16em;display:block;margin-bottom:4px;text-transform:uppercase}.date-value{font-family:'Studio Serif',Georgia,serif;font-size:13px;color:var(--foreground)}
.chapter{margin-top:35px;padding-top:23px;border-top:1px solid var(--line)}.chapter-index{font-family:'Studio Serif',Georgia,serif;font-size:11px;color:var(--accent);font-style:italic}.chapter-heading{font-size:22px;line-height:1.5;letter-spacing:.035em;margin:8px 0 12px}.chapter-caption{font-size:8px;letter-spacing:.18em;color:var(--muted);text-transform:uppercase}.body-copy{white-space:pre-wrap;margin:0;line-height:1.95;font-size:13px}.delivery-heading{display:flex;align-items:flex-start;gap:14px;margin-top:8px}.item-number{font-family:'Studio Serif',Georgia,serif;font-size:25px;color:var(--accent);line-height:1.4}.item-title{font-size:16px;font-weight:500;line-height:1.6;margin:0}.item-format{display:block;font-size:9px;letter-spacing:.12em;color:var(--muted);margin-top:4px}.delivery-copy{color:var(--muted)}.delivery-access{padding:17px;background:var(--panel);margin-top:5px}.access-note{font-size:11px;white-space:pre-wrap;margin:12px 0 0;color:var(--muted)}.delivery-link{display:inline-block;padding:8px 0;margin-right:20px;color:var(--foreground);text-decoration:none;font-size:11px;border-bottom:1px solid var(--accent);word-break:break-all}.link-arrow{padding-left:8px;color:var(--accent)}.qr-links{display:flex;flex-wrap:wrap;justify-content:center;gap:20px}.qr-link{display:flex;align-items:center;flex-direction:column;max-width:100%;text-align:center}.qr-image{width:172px;height:172px;display:block;background:#fff}.qr-label{font-size:12px;margin-top:10px}.qr-host{color:var(--muted);font-size:9px;word-break:break-all}.qr-hint{color:var(--muted);font-size:10px;margin:14px 0 0;text-align:center}
.comparison-unit{margin-top:12px}.comparison-heading{display:flex;justify-content:space-between;gap:10px;align-items:baseline;margin:0 0 13px;font-size:11px;letter-spacing:.04em}.comparison-number{font-family:'Studio Serif',Georgia,serif;color:var(--accent);font-size:16px;font-style:italic;white-space:nowrap}.comparison-pair{display:grid;gap:16px}.comparison-pair.split{grid-template-columns:minmax(0,1fr) minmax(0,1fr);align-items:start}.comparison-pair.stacked{grid-template-columns:1fr}.comparison-figure{margin:0;min-width:0}.comparison-frame{position:relative;width:100%}.comparison-image{display:block;width:100%;height:auto}.comparison-label{display:flex;justify-content:space-between;font-size:8px;letter-spacing:.14em;text-transform:uppercase;color:var(--muted);padding:8px 0 0;gap:8px}.comparison-after .comparison-label{color:var(--accent)}.missing-image{border:1px dashed var(--line);padding:40px 12px;text-align:center;font-size:12px;color:var(--muted)}.comparison-single .comparison-image{max-height:550px;object-fit:contain;object-position:center}.comparison-single{break-before:page}.signature{border-top:1px solid var(--line);padding-top:30px;margin-top:32px;padding-bottom:26px}.signature-mark{font-family:'Studio Serif',Georgia,serif;font-size:40px;font-weight:400;line-height:1.2;letter-spacing:-.04em;margin:12px 0 25px}.signature-name{font-size:12px}.signature-studio{font-size:10px;color:var(--muted);margin-top:4px}.signature-caption{font-size:9px;letter-spacing:.16em;color:var(--accent);text-transform:uppercase}.closing{font-size:9px;letter-spacing:.15em;color:var(--muted);border-top:1px solid var(--line);padding-top:16px;margin-top:30px;text-align:center}
.pdf-page{width:432px;height:768px;padding:32px;break-after:page;background:var(--background);position:relative}.pdf-page:last-child{break-after:auto}.page-masthead{height:36px}.page-body{height:648px;display:flow-root}.page-footer{height:20px;display:flex;justify-content:space-between;align-items:flex-end;font-size:8px;color:var(--muted);letter-spacing:.1em}.pdf-page .chapter:first-child{margin-top:0}.pdf-page .unit{max-width:100%}.pdf-page .cover{min-height:605px}.pdf-pages .flow{display:none}.image-segment{width:432px;padding:32px;background:var(--background);display:flow-root}.image-segment .unit:first-child{margin-top:0}.image-segment-footer{margin-top:16px;padding-top:12px;border-top:1px solid var(--line);font-size:8px;color:var(--muted);display:flex;justify-content:space-between;letter-spacing:.1em}
.cover-ornament{right:32px}
body{font-size:16px}.body-copy{font-size:16px;line-height:1.85}.item-title{font-size:18px}.delivery-link{font-size:14px}.access-note{font-size:14px;line-height:1.85}.comparison-label{font-size:12px;letter-spacing:.09em}.comparison-heading{font-size:13px}.date-value{font-size:15px}.signature-name{font-size:15px}.signature-studio{font-size:12px}.qr-hint{font-size:12px;line-height:1.7}
@page{size:432px 768px;margin:0}@media print{html,body,.render-root{width:432px;margin:0}.pdf-page{box-shadow:none}}
`;
